### PR TITLE
Colab compatibility improvements

### PR DESCRIPTION
**Pull request by AlphaGit**
Hi! I just added these fixes that improve on the Colab compatibility experience.

- Ensure Google Colab GPU Compatibility
  - Added parameters to compile for all available GPU models in Google Colaboratory.
  - Moved the instructions to a common file used by all setup files
  - Adapted Colab file, removing outdated error indicators
- Suppressing compiler warnings
- Updated documentation
  - Updated documentation inside and outside of Colab file.
  - Removed references to any shared Colab file, to avoid outdated versions out there. The one in the `master` branch of this repo should be the canonical one.
  - Added versioning to the file itself, so we can easily tell when someone is using an old version of the file.
  - Added markdown input for configuration

### CODE REVIEW

**Comment by tianchengdw** [comment]
Hi, thank you for your commits, but I meet a error when I use Tesla V100 with compute capability 7.0. 
I change the arch gen-code in the compiler_args.py. However, it seems that it doesn't work.
Thanks in advance!

**Comment by AlphaGit** [comment]
Hi there! It seems like you're on the right path. Did you try adding both the arch and code to 70 compatibility?

Also, I know that this error can also occur on cases where the CUDA drivers are not quite supported -- I'm not entirely sure how to verify that's the case. Around the internet people just keep trying different versions of pytorch, cuda and nvidia drivers until they find a combination that works. What we did is fixed those in Colab to a known working version.

**Comment by tianchengdw** [comment]
Hi,thank you for your reply! 

Yes,I use both the arch and code. First, I fork this repository from your Github. Then I add the 
'-gencode', 'arch=compute_70,code=[sm_70,compute_70]' in the compiler_args.py. At last, I modify the git source in the colab file from my github. But it seems that it is not a useful way.

**Comment by emilwallner** [comment]
I tried it with a V100 on my Colab Pro account, and I had the same error. When I used a non-Colab Pro account, I got a T4 GPU and it worked as expected.

**Pull request merged**
